instance_name: ${instance_name}
kubernetes_namespace: ${kubernetes_namespace}
service_port_1: ${service_port_1}
service_port_2: ${service_port_2}
service_port_3: ${service_port_3}
service_port_4: ${service_port_4}
service_port_5: ${service_port_5}
service_port_6: ${service_port_6}
external_port_1: ${external_port_1}
external_port_2: ${external_port_2}
external_port_3: ${external_port_3}
external_port_4: ${external_port_4}
external_port_5: ${external_port_5}
external_port_6: ${external_port_6}
selector_key: ${selector_key}
selector_value: ${selector_value}
selector_key_2: ${selector_key_2}
selector_value_2: ${selector_value_2}
selector_key_3: ${selector_key_3}
selector_value_3: ${selector_value_3}
ingress_address: ${ingress_address}
